### PR TITLE
change peer dependencies

### PR DESCRIPTION
**Pull request by jaronson13**
I changed the peer dependencies listed in [this story](https://www.pivotaltracker.com/story/show/156161359)

### CODE REVIEW

**Comment by timjklein36** [comment]
Any reason why `platform-browser-dynamic` and `router` aren't `">=4.0.0"` as well?

**Comment by jaronson13** [comment]
They weren't listed in that picture attachment on the story so I assumed they were fine staying the same, but I'm going to change them and see if they can work as >=4.0.0

**Comment by timjklein36** [comment]
Yeah the only reason I mentioned it is because the other angular packages will probably rely on some type of dependency on the same versions for those packages as well.

**Review by timjklein36 — CHANGES_REQUESTED** [review]
Update `platform-browser-dynamic` and `router` dependency versions

**Review by timjklein36 — APPROVED** [review]

**Pull request merged**
